Push output to PR

diff --git a/.github/workflows/terraform-validate.yml b/.github/workflows/terraform-validate.yml
--- a/.github/workflows/terraform-validate.yml
+++ b/.github/workflows/terraform-validate.yml
@@ -1,9 +1,5 @@
 name: "Terraform Validate and Plan"
 
-permissions:
-  id-token: write
-  contents: read
-
 on:
     workflow_call:
         inputs:
@@ -37,7 +33,7 @@ jobs:
             - name: Set up Terraform
               uses: hashicorp/setup-terraform@v1
               with:
-                    terraform_version: ${{ env.TERRAFORM_VERSION }}
+                    terraform_version: ${{ env.TERRAFORM_VERSION }}              
 
             - name: Install tflint & Checkov
               run: |
@@ -64,6 +60,8 @@ jobs:
                   subscription-id: ${{ inputs.oidc-subscription-id }}
 
             - name: Terraform validate and plan
+              id: plan
+              continue-on-error: true
               working-directory: ${{ inputs.example-directory }}
               run: |
                     export ARM_SUBSCRIPTION_ID=${{ inputs.oidc-subscription-id }}
@@ -72,4 +70,47 @@ jobs:
                     export ARM_USE_OIDC=true
                     terraform init -backend=false
                     terraform validate
-                    terraform plan
+                    PLAN=$(terraform plan -no-color -detailed-exitcode | tr '\n' '<br>')
+                    echo "::set-output name=plan::$PLAN"
+
+            - name: Update PR
+              uses: actions/github-script@v7
+              if: github.event_name == 'pull_request'
+
+              id: plan-comment
+              with:
+                script: |
+                    // 1. Retrieve existing bot comments for the PR
+                    const { data: comments } = await github.rest.issues.listComments({
+                      owner: context.repo.owner,
+                      repo: context.repo.repo,
+                      issue_number: context.issue.number,
+                    });
+                    const botComment = comments.find(comment => {
+                      return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan Output')
+                    });
+                    const output = `#### :rocket: Terraform Plan Output
+
+                    \`\`\`
+                    ${{  steps.plan.outputs.plan }}
+                    \`\`\``;
+                    // 3. Delete previous comment so PR timeline makes sense
+                    if (botComment) {
+                      github.rest.issues.deleteComment({
+                        owner: context.repo.owner,
+                        repo: context.repo.repo,
+                        comment_id: botComment.id,
+                      });
+                    }
+                    github.rest.issues.createComment({
+                      issue_number: context.issue.number,
+                      owner: context.repo.owner,
+                      repo: context.repo.repo,
+                      body: output
+                    });
+
+            # TODO
+            # - name: Use terraform plan exit code
+            #   # Terraform plan exit code 0 or 2 are acceptable, see: https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode
+            #   if: steps.plan.outputs.exitcode != 2
+            #   run: exit ${{ steps.plan.outputs.exitcode }}
