Fix exitcode for validate pipeline

diff --git a/.github/workflows/terraform-validate.yml b/.github/workflows/terraform-validate.yml
--- a/.github/workflows/terraform-validate.yml
+++ b/.github/workflows/terraform-validate.yml
@@ -66,14 +66,24 @@ jobs:
               continue-on-error: true
               working-directory: ${{ inputs.example-directory }}
               run: |
-                    export ARM_SUBSCRIPTION_ID=${{ inputs.oidc-subscription-id }}
-                    export ARM_TENANT_ID=${{ inputs.oidc-tenant-id }}
-                    export ARM_CLIENT_ID=${{ inputs.oidc-client-id }}
+                    export ARM_SUBSCRIPTION_ID=0
+                    export ARM_TENANT_ID=0
+                    export ARM_CLIENT_ID=0
                     export ARM_USE_OIDC=true
                     terraform init -backend=false
                     terraform validate
                     PLAN=$(terraform plan -no-color -detailed-exitcode | tr '\n' '<br>')
+
                     echo "::set-output name=plan::$PLAN"
+                    echo "Exit code: ${{ steps.plan.outputs.exitcode }}"
+                    EXIT=${{ steps.plan.outputs.exitcode }}
+                    echo "Exit code: $EXIT"
+                    echo "::set-output name=exit_code::$EXIT"
+
+                  # export ARM_SUBSCRIPTION_ID=${{ inputs.oidc-subscription-id }}
+                  # export ARM_TENANT_ID=${{ inputs.oidc-tenant-id }}
+                  # export ARM_CLIENT_ID=${{ inputs.oidc-client-id }}
+                  # export ARM_USE_OIDC=true
 
             - name: Update PR
               uses: actions/github-script@v7
@@ -111,8 +121,7 @@ jobs:
                       body: output
                     });
 
-            # TODO
-            # - name: Use terraform plan exit code
-            #   # Terraform plan exit code 0 or 2 are acceptable, see: https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode
-            #   if: steps.plan.outputs.exitcode != 2
-            #   run: exit ${{ steps.plan.outputs.exitcode }}
+            - name: Use terraform plan exit code
+              # Terraform plan exit code 0 or 2 are acceptable, see: https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode
+              if: steps.plan.outputs.exit_code != '2'
+              run: exit ${{ steps.plan.outputs.exit_code }}
