Fix exitcode for validate pipeline

diff --git a/.github/workflows/terraform-validate.yml b/.github/workflows/terraform-validate.yml
--- a/.github/workflows/terraform-validate.yml
+++ b/.github/workflows/terraform-validate.yml
@@ -72,8 +72,10 @@ jobs:
                     export ARM_USE_OIDC=true
                     terraform init -backend=false
                     terraform validate
-                    PLAN=$(terraform plan -no-color -detailed-exitcode | tr '\n' '<br>')
-                    echo "::set-output name=plan::$PLAN"
+
+                    plan_output="$(terraform plan -no-color -detailed-exitcode 2>&1 || true)"
+
+                    echo "::set-output name=plan::$(echo "$plan_output" | sed 's/\\n/<br>/g')"
 
             - name: Update PR
               uses: actions/github-script@v7
@@ -111,8 +113,7 @@ jobs:
                       body: output
                     });
 
-            # TODO
-            # - name: Use terraform plan exit code
-            #   # Terraform plan exit code 0 or 2 are acceptable, see: https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode
-            #   if: steps.plan.outputs.exitcode != 2
-            #   run: exit ${{ steps.plan.outputs.exitcode }}
+            - name: Use terraform plan exit code
+              # Terraform plan exit code 0 or 2 are acceptable, see: https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode
+              if: steps.plan.outputs.exitcode != '2'
+              run: exit ${{ steps.plan.outputs.exitcode }}
